{% set name = "tldr" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tldr-pages/tldr-python-client/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2e974b28d460ae1e8ade0ede92f96c2c564205daa0e0e7360b15d3fb5c576203

build:
  number: 0
  noarch: python
  entry_points:
    - tldr = tldr:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - shtab
    - colorama
    - python >=3.7
    - termcolor

test:
  commands:
    - tldr --help

about:
  home: https://github.com/tldr-pages/tldr-python-client
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: command line client for tldr

extra:
  recipe-maintainers:
    - izahn
